export default {
	namespaced: true,
	state: {
		items: [
			{
				id: 1,
				img: 'img',
				type: 'Салон красоты',
				name: 'Vse Svoi',
				address: 'ул.Фурманова, д.248, 2 этаж, 222 каб. офис 441',
				itemNumber: 27,
			},
			{
				id: 2,
				img: 'img',
				type: 'Салон красоты',
				name: 'Lilu',
				address: 'ул. Байтурсынова 90, уг. пр. Абая',
				itemNumber: 59,
			},
			{
				id: 3,
				img: 'img',
				type: 'Барбершоп',
				name: 'Ханская Бритва',
				address: 'пр. Назарбаева, 77',
				itemNumber: 46,
			},
			{
				id: 4,
				img: 'img',
				type: 'Студия красоты',
				name: 'Nailfie.Kz',
				address: 'мкр. Самал 2, д. 56а',
				itemNumber: 74,
			},
			{
				id:5,
				img: 'img',
				type: 'Студия красоты',
				name: 'Beauty Bar by Adel Ardashirova',
				address: 'Розыбакиева 247, ЖК Вавилон, корпус 2. (вход со стороны Розыбакиева)',
				itemNumber: 47,
			},
			{
				id: 6,
				img: 'img',
				type: 'Салон красоты',
				name: 'Шик by nail bar Almaty',
				address: 'ул. Курмангазы, 113, между ул. Байтурсынова ул.Шарипова',
				itemNumber: 42,
			},
			{
				id: 7,
				img: 'img',
				type: 'Салон красоты',
				name: 'Zoloto',
				address: 'ул. Богенбай батыра,106',
				itemNumber: 18,
			},
			{
				id: 8,
				img: 'img',
				type: 'Салон красоты',
				name: 'Kuze',
				address: 'ул. Тынышбаева д. 3',
				itemNumber: 128,
			},
			{
				id: 9,
				img: 'img',
				type: 'Салон красоты для детей',
				name: 'СтильНяшки ТРЦ «Спутник»',
				address: 'ТРЦ «Спутник», 3 этаж',
				itemNumber: 40,
			},
			{
				id: 10,
				img: 'img',
				type: 'Салон красоты',
				name: 'Adina',
				address: 'мкр. Мамыр1, здание 29/4',
				itemNumber: 19,
			},
			{
				id: 11,
				img: 'img',
				type: 'Салон красоты',
				name: 'Beauty Territory',
				address: 'ул. Розыбакиева, 247 ТРЦ Мега',
				itemNumber: 17,
			},
			{
				id: 12,
				img: 'img',
				type: 'Салон красоты',
				name: ' Принцесс By Nail Bar Almaty',
				address: 'ул. Жамбыла 105/81',
				itemNumber: 75,
			},
			{
				id: 13,
				img: 'img',
				type: 'Салон красоты',
				name: 'АнАри',
				address: 'пр. Бухар Жырау, 6',
				itemNumber: 6,
			},
			{
				id: 14,
				img: 'img',
				type: 'Студия красоты',
				name: 'Beauty Lab  Shakhizat Alpisheva',
				address: 'ул. Сатпаева 30а/3',
				itemNumber: 28,
			},
			{
				id: 15,
				img: 'img',
				type: 'Салон красоты',
				name: 'Heaven',
				address: 'г. Алматы, ул Сатпаева,3 /Валиханова 170',
				itemNumber: 40,
			},
			{
				id: 16,
				img: 'img',
				type: 'Салон красоты',
				name: 'Apple room',
				address: 'ул. Жарокова, 169',
				itemNumber: 13,
			},
			{
				id: 17,
				img: 'img',
				type: 'Салон красоты',
				name: 'Шикарный',
				address: 'пр. Абылай хана, 64',
				itemNumber: 28,
			},
			{
				id: 18,
				img: 'img',
				type: 'Студия красоты',
				name: 'Aiya_eyebrows ',
				address: 'ул. Розыбакиева, 247',
				itemNumber: 14,
			},
			{
				id: 19,
				img: 'img',
				type: 'Салон красоты',
				name: 'NG',
				address: 'БЦ Жел Тау, ул. Егизбаева, 7в',
				itemNumber: 10,
			},
			{
				id: 20,
				img: 'img',
				type: 'Студия красоты',
				name: 'My Way Tattoo ',
				address: 'ул. Назарбаева, 118',
				itemNumber: '',
			},
			{
				id: 21,
				img: 'img',
				type: 'Салон красоты',
				name: 'Әдемі',
				address: 'пр. Абая 204',
				itemNumber: '',
			},
			{
				id: 22,
				img: 'img',
				type: 'Салон красоты',
				name: 'Красотка ',
				address: 'ул. Жарокова, 209',
				itemNumber: 12,
			},
			{
				id: 23,
				img: 'img',
				type: 'Студия красоты',
				name: 'ЗинАн',
				address: 'ул. Демьяна Бедного №3 / ул. Джангильдина угол ул. Рыскулова',
				itemNumber: 16,
			},
			{
				id: 24,
				img: 'img',
				type: 'Салон красоты',
				name: 'Divine',
				address: 'Пр.Абая 20/1',
				itemNumber: '',
			},
			{
				id: 25,
				img: 'img',
				type: 'Студия красоты',
				name: 'KRASNOE YABLOKO от Саши Харитоновой ',
				address: 'ул. Гоголя, 74',
				itemNumber: 131,
			},
			{
				id: 26,
				img: 'img',
				type: 'Салон красоты',
				name: 'Mi lash',
				address: ' ул. Казыбек би 125, уг. ул. Досмухамедова',
				itemNumber: 11,
			},
			{
				id: 27,
				img: 'img',
				type: 'Салон красоты',
				name: 'Zhazira',
				address: 'ул. Валиханова, 84',
				itemNumber: 32,
			},
			{
				id: 28,
				img: 'img',
				type: 'Салон красоты',
				name: 'Concept Centre For You',
				address: 'Ул. Ауэзова, 163',
				itemNumber: 36,
			},
			{
				id: 29,
				img: 'img',
				type: 'Салон красоты',
				name: 'Lilu  2',
				address: 'ул. Толе би 192, уг. пр. Гагарина',
				itemNumber: 14,
			},
			
		],
	},
	getters: {
		items(state) {
			return state.items;
		}
	},
}
